apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{- .Release.Name }}
  labels:
    {{- include  "python_app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "python_app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "python_app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: {{ .Values.env.name }}
            value: {{ .Values.env.value }}