apiVersion: v1
kind: Pod
metadata:
  labels:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  name: {{- .Values.redis_name }}
spec:
  containers:
  - image: "{{- .Values.image.redis_pod }}:{{ .Values.image.redis_tag | default "latest" }}"
    name: {{- .Values.redis_name }}
    resources: {}
  dnsPolicy: ClusterFirst
status: {}