apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  name: {{- .Values.redis_name }}
spec:
  type: {{- .Values.service_redis.type }}
  ports:
  - port: {{- .Values.service_redis.port}}
    protocol: TCP
    name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}