apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.name }}
  labels:
    {{- include "python_app.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "python_app.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
